### ISSUE TITLE
Small corrections

### ISSUE THREAD

**Issue by AndyL4N** [ThomasOliver545/nestjs-auth-jwt#1]
Hi @ThomasOliver545 ,
At first I would like to thank you for you excellent lessons! This is very helpfull for beginers in nest.

But recently I've found a couple issues with some functions for user registration and login. So I think to share it with you.

In the file `user.entity.ts` here is 
```
    @BeforeInsert()
    @BeforeUpdate()
    emailToLowerCase() {
        this.email = this.email.toLowerCase();
    }
```
In my implementation this didn't work until I found this issue: [https://github.com/typeorm/typeorm/issues/674 ](https://github.com/typeorm/typeorm/issues/674 ). To be short, these typeorm event listerners work only if entity is instanciated.

Just for example (in `user.service.ts`): 
```
 create(createdUserDto: CreateUserDto): Observable<UserI> {
        const createdUserEntity = this.userRepository.create(createdUserDto); //  <==== OR 
       // const  createdUserEntity=  Object.assign(new CreatedUserDto(), createdUserDto)  // <=== THIS
        return this.mailExists(createdUserEntity.email).pipe(
            switchMap((exists: boolean) => {
                if (!exists) {
                    return this.authService.hashPassword(createdUserEntity.password).pipe(
```
In this case it works. Probably you already know more elegant solution.

And related question is about login. We transform email to lower case on saving. But don't you think it will be good to transform same way in login function before searching by email?

I hope it can be useful.

**Comment by TommiCodes** [comment]
> Hi @ThomasOliver545 , At first I would like to thank you for you excellent lessons! This is very helpfull for beginers in nest.
> 
> But recently I've found a couple issues with some functions for user registration and login. So I think to share it with you.
> 
> In the file `user.entity.ts` here is
> 
> ```
>     @BeforeInsert()
>     @BeforeUpdate()
>     emailToLowerCase() {
>         this.email = this.email.toLowerCase();
>     }
> ```
> 
> In my implementation this didn't work until I found this issue: [https://github.com/typeorm/typeorm/issues/674 ](https://github.com/typeorm/typeorm/issues/674). To be short, these typeorm event listerners work only if entity is instanciated.
> 
> Just for example (in `user.service.ts`):
> 
> ```
>  create(createdUserDto: CreateUserDto): Observable<UserI> {
>         const createdUserEntity = this.userRepository.create(createdUserDto); //  <==== OR 
>        // const  createdUserEntity=  Object.assign(new CreatedUserDto(), createdUserDto)  // <=== THIS
>         return this.mailExists(createdUserEntity.email).pipe(
>             switchMap((exists: boolean) => {
>                 if (!exists) {
>                     return this.authService.hashPassword(createdUserEntity.password).pipe(
> ```
> 
> In this case it works. Probably you already know more elegant solution.
> 
> And related question is about login. We transform email to lower case on saving. But don't you think it will be good to transform same way in login function before searching by email?
> 
> I hope it can be useful.

Hi @AndyL4N,

all your suggestions are absolutely correct.
Sorry that i missed your Issue the last months.

I just made a commit that is fixing the issue.

The email is now being handled as lowercase.
With User Creation we first create a UserEntity, so that the Insert and Update Listeners will work.
With the Login we also make sure, that the email is always converted to lowercase, so that the specific user will be found.

Happy new Year and thanks for this issue and the great hints.

FR 
Thomas :)
